########################################################################################################################
################################################# grid configuration ###################################################
########################################################################################################################

grids:
  electricity:                          # type of grid (needs to match available grid types)
    powerflow: dc                       # type of powerflow
                                        # options:
                                        #   - dc: direct current
                                        #   - ac: alternating current (not implemented yet)

    active: True                        # is the grid active?
                                        # options:
                                        #   - True: grid is active and will be calculated during simulation
                                        #   - False: grid is inactive and will be ignored during simulation

    method: topology                    # grid creation method
                                        # options:
                                        #   - file: create grid from file
                                        #   - topology: create scenario first, then user has to assign agent-id to bus
                                        #     in 'topology.xlsx' file

    file:                               # file method settings
      file: electricity.xlsx            # file containing the grid
                                        # file types: xlsx
                                        # note: needs to be in the same folder as this file

    topology:                           # topology method settings
      file: topology.xlsx               # file containing the topology
                                        # file types: xlsx
                                        # note: needs to be in the same folder as this file

    variable_grid_fees:
      active: False

      horizon: 86400                    # variable grid fees calculation horizon
                                        # unit: s

      update: 3600                      # variable grid fees update frequency
                                        # unit: s

    direct_power_control:
      active: False

      control: individual               # types of direct power control
                                        # individual: control individual devices
                                        # ems: control via EMS

      max_iteration: 10                 # maximal number of iteration

  heat:
    active: False

  hydrogen:
    active: False